# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb3ba62956104baf3768ff557bca3ccff6fd65560c0dcaf6ecff4fada36d183aa1c3ec47882cd1d16ce35568637a8ac89f0d9ccc83fb3d27b9a73510a4c1d87f

test:
  secret_key_base: 8941268cea23fe17a69224b1f2a9da965b534ed93c203ac35b21b0a4178339062bb124279eea0e1ea5c74a40ff77f9dda9371b1154cab632bc4c1f7805dce1b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
